version: "3.1"
services:
  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - ../:/application:delegated
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini

  nginx:
    image: nginx:alpine
    volumes:
      - ../:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql:delegated
      - ./mysql/auth-plugin.cnf:/etc/mysql/conf.d/auth-plugin.cnf:cached
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"

networks:
  default:
    name: boojbooks

volumes:
  mysql-data:
